#version 460

struct IndexedIndirectCommand 
{
	uint indexCount;
	uint instanceCount;
	uint firstIndex;
	uint vertexOffset;
	uint firstInstance;
};

struct AABB {
	vec4 min;
	vec4 max;
};

layout(set = 0, binding = 0) uniform UBO 
{
	vec4 frustumPlanes[14];
} ubo;	

layout(std430, set = 0, binding = 1) buffer OutputIndirectDraws {
	IndexedIndirectCommand indirectDrawsOut[];
};

layout(std430, set = 0, binding = 2) readonly buffer BoundingBoxes {
	AABB boxes[];
};

layout(std430, set = 0, binding = 3) readonly buffer ModelMatrices {
	mat4 modelMatrices[];
};

layout(push_constant) uniform pushConstant
{
    int numDraws;
} pcs;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

bool frustumCheck(vec4 min, vec4 max)
{
	for (int i = 0; i < 6; i++) {
		int num = 0;
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, min.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, min.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, max.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, max.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, min.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, min.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, max.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, max.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		if (num == 8) return false;
    	}

	// Check frustum outside/inside box
	//int num;
	//num = 0; for (int i = 6; i < 14; i++) num += ((ubo.frustumPlanes[i].x > max.x) ? 1 : 0); if (num == 8) return false;
	//num = 0; for (int i = 6; i < 14; i++) num += ((ubo.frustumPlanes[i].x < min.x) ? 1 : 0); if (num == 8) return false;
	//num = 0; for (int i = 6; i < 14; i++) num += ((ubo.frustumPlanes[i].y > max.y) ? 1 : 0); if (num == 8) return false;
	//num = 0; for (int i = 6; i < 14; i++) num += ((ubo.frustumPlanes[i].y < min.y) ? 1 : 0); if (num == 8) return false;
	//num = 0; for (int i = 6; i < 14; i++) num += ((ubo.frustumPlanes[i].z > max.z) ? 1 : 0); if (num == 8) return false;
	//num = 0; for (int i = 6; i < 14; i++) num += ((ubo.frustumPlanes[i].z < min.z) ? 1 : 0); if (num == 8) return false;

	return true;
}

void main()
{
   	uint idx = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_NumWorkGroups.x * gl_WorkGroupSize.x;

	if (idx >= pcs.numDraws) {
        	return;
    	}

	mat4 modelMatrix = modelMatrices[idx];

	vec4 currentMin = modelMatrix * boxes[idx].min;
	vec4 currentMax = modelMatrix * boxes[idx].max;

   	if (frustumCheck(currentMin, currentMax)) 
	{
		indirectDrawsOut[idx].instanceCount = 1; // if visible, set the draw instance count to 1
	}
	else{
		indirectDrawsOut[idx].instanceCount = 0; // if not visible, set the draw instance count to 0
	}
}